[bootstrap.mise_shell_activate]
zprofile = "shims"
zshrc = "activate"

[bootstrap.services.mise-history]
builtin = "history-watch"

[bootstrap.packages]
"brew-cask:zed" = "latest"

[dotfiles]
"~/.bootstrap.dummy" = { mode = "track" }
"~/.config/mise/config.toml" = { mode = "track" }

[tools]
gh = "latest"
